.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,7 +7,9 @@ on:
   workflow_dispatch:
     inputs:
       target_subproject:
-        description: The subproject name of the specified Minecraft version to be released.
+        description: |-
+          The subproject name(s) of the specified Minecraft version to be released, seperated with ",".
+          By default all subprojects will be released
         type: string
         required: false
         default: ''
@@ -25,8 +27,8 @@ jobs:
         run: |
           cat <<EOF > $GITHUB_STEP_SUMMARY
           ## Action Parameters
-          - target_subproject: `${{ github.event.inputs.target_subproject }}`
-          - target_release_tag: `${{ github.event.inputs.target_release_tag }}`
+          - target_subproject: \`${{ github.event.inputs.target_subproject }}\`
+          - target_release_tag: \`${{ github.event.inputs.target_release_tag }}\`
           EOF
 
   matrix_prep:
@@ -56,6 +58,12 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+
+      - name: Display context
+        run: |
+          echo ref_name = ${{ github.ref_name }}
+          echo target_subproject = ${{ github.event.inputs.target_subproject }}
+          echo target_release_tag = ${{ github.event.inputs.target_release_tag }}
 
       - name: Download build artifacts
         uses: actions/download-artifact@v3
@@ -97,7 +105,7 @@ jobs:
         id: properties_v
         uses: christian-draeger/read-properties@1.1.1
         with:
-          path: ${{ format('versions/{0}/gradle.properties', matrix.subproject_dir) }}
+          path: ${{ format('versions/{0}/gradle.properties', matrix.subproject) }}
           properties: 'minecraft_version game_versions'
 
       - name: Fix game version
@@ -107,6 +115,42 @@ jobs:
           echo 'value<<EOF' >> $GITHUB_OUTPUT
           echo -e "${{ steps.properties_v.outputs.game_versions }}" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
+
+      - name: Prepare file information
+        id: file_info
+        run: |
+          shopt -s extglob
+          FILE_PATHS=$(ls ${{ format('build-artifacts/{0}/build/libs/!(*-@(dev|sources|shadow)).jar', matrix.subproject) }})
+          if (( ${#FILE_PATHS[@]} != 1 )); then
+              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
+              exit 1
+          else
+              FILE_PATH=${FILE_PATHS[0]}
+          fi
+          
+          FILE_NAME=$(basename $FILE_PATH)
+          FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
+          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
+          echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
+          echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+      - name: Prepare changelog
+        uses: actions/github-script@v6
+        id: changelog
+        with:
+          script: return process.env.CHANGELOG
+          result-encoding: string
+        env:
+          CHANGELOG: |-
+            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+            
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
       - name: Publish Minecraft Mods
         uses: Kir-Antipov/mc-publish@v3.3
